[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[testnet]
json_rpc_url = "https://rpc.gorbagana.wtf"  
websocket_url = "wss://rpc.gorbagana.wtf"

[programs.testnet]
trivia_battle = "7ZAriVE481w9CGmpeHwFVztJ1oUiLFvFzUPNuVutvxKA"

[provider]
cluster = "https://rpc.gorbagana.wtf"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"